title:              Engineering Portfolio
email:              choang@olin.edu
description:        A work in progress
author:             Connor Hoang
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://CDHoang.github.io"

# Social Profiles
twitter_username:   
github_username:    CDHoang
facebook_username:  
instagram_username:  
linkedin_username: cdhoang

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
